export enum AchievementId {
  FirstDigestion = "first_digestion",
  Engulf20 = "engulf_20",
  Devour50 = "devour_50",
  ReachLevel5 = "reach_level_5",
  Survive180s = "survive_180s",
  GiantVolume = "giant_volume",
  FullArsenal = "full_arsenal",
  FirstEvolution = "first_evolution",
  PrionCleared = "prion_cleared",
  WoundClear = "wound_clear",
  AlveolarClear = "alveolar_clear",
  HepaticClear = "hepatic_clear",
  GastricClear = "gastric_clear",
  BbbClear = "bbb_clear",
  WoundHardClear = "wound_hard_clear",
  AlveolarHardClear = "alveolar_hard_clear",
  HepaticHardClear = "hepatic_hard_clear",
  GastricHardClear = "gastric_hard_clear",
  BbbHardClear = "bbb_hard_clear",
}

export enum AchievementStatKey {
  ActiveSkills = "active_skills",
  FirstEvolution = "first_evolution",
  Kills = "kills",
  Level = "level",
  MapClearAcuteWound = "map_clear_acute_wound",
  MapClearAcuteWoundHard = "map_clear_acute_wound_hard",
  MapClearAlveolarSpace = "map_clear_alveolar_space",
  MapClearAlveolarSpaceHard = "map_clear_alveolar_space_hard",
  MapClearBloodBrainBarrier = "map_clear_blood_brain_barrier",
  MapClearBloodBrainBarrierHard = "map_clear_blood_brain_barrier_hard",
  MapClearGastricLumen = "map_clear_gastric_lumen",
  MapClearGastricLumenHard = "map_clear_gastric_lumen_hard",
  MapClearHepaticSinusoid = "map_clear_hepatic_sinusoid",
  MapClearHepaticSinusoidHard = "map_clear_hepatic_sinusoid_hard",
  PrionCleared = "prion_cleared",
  RadiusRatio = "radius_ratio",
  SurvivalTime = "survival_time",
}
