export enum SfxId {
  Hit = "hit",
  HitCrit = "hit_crit",
  PlayerHit = "player_hit",
  Death = "death",
  DiePlayer = "die_player",
  LevelUpgrade = "level_upgrade",
  ItemPickup = "item_pickup",
  Shoot = "shoot",
  UiClick = "ui_click",
  UiConfirm = "ui_confirm",
  WaveComplete = "wave_complete",
  WaveStart = "wave_start",
  GameStart = "game_start",
  GameOver = "game_over",
  Explosion = "explosion",
  HitSwordSmall = "hit_sword_small",
  FlameDash = "flame_dash",
  ExtraCoin = "extra_coin",
  GemSocket = "gem_socket",
  ItemDrop = "item_drop",
  UiError02 = "ui_error_02",
  HeavyStrike = "heavy_strike",
  HolyBolt = "holy_bolt",
  SplitArrowFire = "split_arrow_fire",
  DischargeBlast = "discharge_blast",
  ScorchingRay = "scorching_ray",
  Desecrate = "desecrate",
  Incinerate = "incinerate",
  IcicleMine = "icicle_mine",
  GroundSlam = "ground_slam",
  ShockNova = "shock_nova",
  EtherealKnives = "ethereal_knives",
  IceNova = "ice_nova",
  ColdSnap = "cold_snap",
  ToxicRain = "toxic_rain",
  Spark = "spark",
  Vortex = "vortex",
}

export enum BgmId {
  Menu = "menu",
  BattleBgm = "battle_bgm",
  BattleBgm2 = "battle_bgm_2",
  Boss = "boss",
  BossFinal = "boss_final",
  Victory = "victory",
  Defeat = "defeat",
  EchoesOfTheAether = "echoes_of_the_aether",
  Swamp = "swamp",
  Crypt = "crypt",
  Dimension = "dimension",
}
