export enum EnemyId {
  Staph = "staph",
  Norovirus = "norovirus",
  SVirus = "s_virus",
  FluDrift = "flu_drift",
  MalignantCell = "malignant_cell",
  Pseudomonas = "pseudomonas",
  EColi = "e_coli",
  Tb = "tb",
  Tetanus = "tetanus",
  HPylori = "h_pylori",
  AnthraxSpore = "anthrax_spore",
  AnthraxBacillus = "anthrax_bacillus",
  Hiv = "hiv",
  Rabies = "rabies",
  Ebola = "ebola",
  VaricellaZoster = "varicella_zoster",
  Candida = "candida",
  Aspergillus = "aspergillus",
  Plasmodium = "plasmodium",
  PlasmodiumMerozoite = "plasmodium_merozoite",
  Toxoplasma = "toxoplasma",
  Prion = "prion",
  PrionFragment = "prion_fragment",
  StreptococcusChainLord = "streptococcus_chain_lord",
  FluDriftCyclone = "flu_drift_cyclone",
  TbGranulomaBehemoth = "tb_granuloma_behemoth",
  VacaSecretor = "vaca_secretor",
  ToxoplasmaMegaCyst = "toxoplasma_mega_cyst",
  Tachyzoite = "tachyzoite",
  MrsaSuperColony = "mrsa_super_colony",
  MrsaEnragedElite = "mrsa_enraged_elite",
  SyncytialMegaCapsid = "syncytial_mega_capsid",
  PlasmodiumMacroSchizont = "plasmodium_macro_schizont",
  HPyloriBiofilmCore = "hpylori_biofilm_core",
  PrpscAmyloidAggregate = "prpsc_amyloid_aggregate",
}

export enum ThreatMode {
  ChemoChaser = "ChemoChaser",
  Drifter = "Drifter",
  Interceptor = "Interceptor",
  Invader = "Invader",
  Standoff = "Standoff",
}
