export enum GearId {
  MitochondriaMkii = "mitochondria_mkii",
  GlycolyticBypass = "glycolytic_bypass",
  AcidicLysosome = "acidic_lysosome",
  ProteasomeSieve = "proteasome_sieve",
  FlagellarBase = "flagellar_base",
  MicrotubuleAnchor = "microtubule_anchor",
  RoughEr = "rough_er",
  RibosomeCluster = "ribosome_cluster",
  IonChannelArray = "ion_channel_array",
  ChemokinePatch = "chemokine_patch",
  SymbioticFlora = "symbiotic_flora",
  PhageFragment = "phage_fragment",
  AtpShuttle = "atp_shuttle",
  KrebsCycle = "krebs_cycle",
  BileSaltPool = "bile_salt_pool",
  PhagolysosomeCore = "phagolysosome_core",
  ActinMesh = "actin_mesh",
  CentrosomeArray = "centrosome_array",
  GolgiStack = "golgi_stack",
  NucleolusPrime = "nucleolus_prime",
  TollReceptor = "toll_receptor",
  MembraneRaft = "membrane_raft",
  RedoxSymbiont = "redox_symbiont",
  QuorumColony = "quorum_colony",
}

export enum GearCategory {
  Cytoskeleton = "cytoskeleton",
  Digestion = "digestion",
  Metabolism = "metabolism",
  Sensing = "sensing",
  Symbiosis = "symbiosis",
  Synthesis = "synthesis",
}
