export enum SkillId {
  PhagocyticGrasp = "phagocytic_grasp",
  LysosomalOverload = "lysosomal_overload",
  RosTorrent = "ros_torrent",
  PerforinLance = "perforin_lance",
  ComplementCascade = "complement_cascade",
  AntibodySalvo = "antibody_salvo",
  PseudopodLunge = "pseudopod_lunge",
  NitricOxideHalo = "nitric_oxide_halo",
  NucleaseBlades = "nuclease_blades",
  GranzymeDetonation = "granzyme_detonation",
  InterferonWave = "interferon_wave",
  LysozymeRicochet = "lysozyme_ricochet",
  PhagolysosomeVent = "phagolysosome_vent",
  ProInflammatoryArc = "pro_inflammatory_arc",
  ExosomeSingularity = "exosome_singularity",
  DefensinBarbs = "defensin_barbs",
  MhcTracerBeam = "mhc_tracer_beam",
  HistamineSurge = "histamine_surge",
  Actin = "actin",
  Lysosome = "lysosome",
  Mitochondria = "mitochondria",
  Opsonin = "opsonin",
  Chemokine = "chemokine",
  Bilayer = "bilayer",
  Autophagy = "autophagy",
  Glycolysis = "glycolysis",
  Kinesin = "kinesin",
  Longevity = "longevity",
  Vdj = "vdj",
  Endotoxin = "endotoxin",
  Hematopoietic = "hematopoietic",
}

export enum SkillArchetype {
  Strike = "strike",
  Salvo = "salvo",
  Beam = "beam",
  Aura = "aura",
  Zone = "zone",
  Nova = "nova",
  Passive = "passive",
}

export enum SkillType {
  Active = "active",
  Innate = "innate",
  Passive = "passive",
}
