export enum StatId {
  Might = "might",
  Area = "area",
  CooldownReduction = "cooldown_reduction",
  ProjectileSpeed = "projectile_speed",
  Duration = "duration",
  Amount = "amount",
  Pierce = "pierce",
  CritChance = "crit_chance",
  CritDamage = "crit_damage",
  ArmorPenetration = "armor_penetration",
  AilmentChance = "ailment_chance",
  AilmentThreshold = "ailment_threshold",
  AilmentEffect = "ailment_effect",
  DotDamage = "dot_damage",
  PhysicalDamage = "physical_damage",
  FireDamage = "fire_damage",
  ColdDamage = "cold_damage",
  LightningDamage = "lightning_damage",
  ChaosDamage = "chaos_damage",
  MeleeDamage = "melee_damage",
  SpellDamage = "spell_damage",
  AoeDamage = "aoe_damage",
  ProjectileDamage = "projectile_damage",
  MinionDamage = "minion_damage",
  MaxHealth = "max_health",
  HealthRegen = "health_regen",
  Armor = "armor",
  DamageTaken = "damage_taken",
  MoveSpeed = "move_speed",
  Evasion = "evasion",
  Block = "block",
  LifeSteal = "life_steal",
  Magnet = "magnet",
  Stagger = "stagger",
  Recoup = "recoup",
}

export enum ModType {
  Flat = "flat",
  Percent = "percent",
  PercentagePoints = "percentagepoints",
}

export enum PassiveModMode {
  Flat = "flat",
  FlatOnce = "flat_once",
  Mult = "mult",
}
