export enum TraitId {
  Actin = "actin",
  Autophagy = "autophagy",
  Bilayer = "bilayer",
  Chemokine = "chemokine",
  Endotoxin = "endotoxin",
  Glycolysis = "glycolysis",
  Hematopoietic = "hematopoietic",
  Kinesin = "kinesin",
  Longevity = "longevity",
  Lysosome = "lysosome",
  Mitochondria = "mitochondria",
  Opsonin = "opsonin",
  Vdj = "vdj",
  SmallArea = "small_area",
  SmallMagnet = "small_magnet",
  SmallMight = "small_might",
  SmallMoveSpeed = "small_move_speed",
  SmallProjectileSpeed = "small_projectile_speed",
  AdaptiveOverdrive = "adaptive_overdrive",
  AerobicSprint = "aerobic_sprint",
  AntigenHarvest = "antigen_harvest",
  AssassinsMandate = "assassins_mandate",
  BallisticThreads = "ballistic_threads",
  BloodPrice = "blood_price",
  ContainedFury = "contained_fury",
  CytoskeletalDrift = "cytoskeletal_drift",
  DeepWound = "deep_wound",
  EnduringMarch = "enduring_march",
  ExecutionTempo = "execution_tempo",
  ExtendedChambers = "extended_chambers",
  FarSense = "far_sense",
  GuidedSalvo = "guided_salvo",
  ImmortalCulture = "immortal_culture",
  IronMembrane = "iron_membrane",
  LightfootedKiller = "lightfooted_killer",
  LuckyMutation = "lucky_mutation",
  MarkedCore = "marked_core",
  OmnipotentCytoplasm = "omnipotent_cytoplasm",
  OverdrawnStrings = "overdrawn_strings",
  OxidativePace = "oxidative_pace",
  PatientObserver = "patient_observer",
  PiercingFilaments = "piercing_filaments",
  PreciseEdge = "precise_edge",
  PseudopodMarathon = "pseudopod_marathon",
  RapidClotting = "rapid_clotting",
  RapidReposition = "rapid_reposition",
  RiskAssessment = "risk_assessment",
  RollingThunder = "rolling_thunder",
  ScavengerField = "scavenger_field",
  SecondWind = "second_wind",
  Slipstream = "slipstream",
  SplittingVolley = "splitting_volley",
  SwarmCartography = "swarm_cartography",
  ThickCytoplasm = "thick_cytoplasm",
}

export enum TraitRarity {
  Start = "start",
  Magic = "magic",
  Normal = "normal",
  Rare = "rare",
  Unique = "unique",
}

export enum TraitBranch {
  Precision = "precision",
  Senses = "senses",
  Motility = "motility",
  Ballistics = "ballistics",
  Vitality = "vitality",
  Core = "core",
}
