export enum UiId {
  BadgeAntigen = "badge_antigen",
  BadgeAtp = "badge_atp",
  ButtonPause = "button_pause",
  ButtonSettings = "button_settings",
  CardMutation = "card_mutation",
  CardSuperweapon = "card_superweapon",
  FrameOrganelle = "frame_organelle",
  MeterPh = "meter_ph",
  MeterTemp = "meter_temp",
  ReticleDanger = "reticle_danger",
  ReticleScan = "reticle_scan",
  ReticleTarget = "reticle_target",
  StatusBuffered = "status_buffered",
  StatusExhausted = "status_exhausted",
  StatusInflamed = "status_inflamed",
  StatusOverclock = "status_overclock",
}
